Feature/login
SamuelSsc/Onboarding-Instituto pull request #9
Opened 2022-01-20 12:37 UTC by SamuelSsc

Tela de Login solicitada na Track 3/8 Step 1/2.

2022-01-20 13:18 UTC, dan-ueno requested changes
Você não vai usar o css para posicionamento, abre um arquivo type e cria uma estilização com styled-components para o componente

2022-01-20 13:18 UTC, dan-ueno commented on src/index.tsx
> +    <Login />
aqui vc deixa como está, dentro do App vc cria o componente de login

2022-01-20 17:37 UTC, SamuelSsc commented on src/index.tsx
> +    <Login />
Tentei arrumar a estrutura e estilizar com o Style components, estou vendo agr como arrumar a questão do Networking dando uma pesquisada naqueles comandos de git de ontem.

2022-01-20 22:44 UTC, dan-ueno requested changes

2022-01-20 22:44 UTC, dan-ueno commented on src/components/valida_login.js
> +    var input = document.querySelector ("#email");
regex =]

2022-01-20 22:45 UTC, dan-ueno commented on src/Login.css
> +.form{
deleta o arquivo css

2022-01-20 22:45 UTC, dan-ueno commented on src/components/Login.tsx
> +import React from "react";
ele é um componente, então o nome tem q ser login.component.tsx

2022-01-20 22:46 UTC, dan-ueno commented on src/components/style.ts
> +import styled from 'styled-components';
ele é o styled de um componente, então o nome fica login.component.style.tsx

2022-01-21 12:30 UTC, SamuelSsc commented on src/components/valida_login.js
> +    var input = document.querySelector ("#email");
implementado

2022-01-21 12:30 UTC, SamuelSsc commented on src/Login.css
> +.form{
excluído

2022-01-21 12:31 UTC, SamuelSsc commented on src/components/style.ts
> +import styled from 'styled-components';
estrutura melhorada, estou vendo a questão do POST para implementar.

2022-01-21 13:40 UTC, dan-ueno requested changes

2022-01-21 13:40 UTC, dan-ueno commented on src/components/Login/Login.component.tsx
> +      <Button id="btnEntrar" onClick={ValidarLogin} type="submit" >Entrar</Button>
aqui é o que eu tinha comentado ontem, dá uma olhada em Regex e pode deletar o arquivo de valida_login, a função mais pra frente com a requisição vai ficar dentro do componente mesmo.

2022-01-21 13:40 UTC, dan-ueno commented on src/components/Login/valida_login.js
> +    var input = document.querySelector ("#email");
aqui vc vai deletar essa função. mas é importante lembrar que as duas variaveis que no geral vc vai criar são let e const, evita usar var

2022-01-21 13:40 UTC, dan-ueno commented on src/components/Login/Login.component.tsx
> +    <Forms id="Forms" method="POST">
pq tem um method post no seu form??

2022-01-21 13:40 UTC, dan-ueno commented on package.json
> +    "styled-components": "^5.3.3"
aqui  é o que tinha comentado, para o projeto de onboard não ia ficar falando para tirar o ^. mas se vc tirou de alguns, tira de todos hahaahahaha. Padrão é importante, é estranho em algumas libs estar a versão específica como no prettier e outras aceitar versões próximas

2022-01-21 13:52 UTC, SamuelSsc commented on src/components/Login/Login.component.tsx
> +      <Button id="btnEntrar" onClick={ValidarLogin} type="submit" >Entrar</Button>
ah sim, então as functions eu posso colocar no mesmo arquivo do componente?

2022-01-21 13:53 UTC, SamuelSsc commented on src/components/Login/valida_login.js
> +    var input = document.querySelector ("#email");
ahh blz, var da problema no escopo né?! haha

2022-01-21 13:55 UTC, SamuelSsc commented on src/components/Login/Login.component.tsx
> +    <Forms id="Forms" method="POST">
kkkk tinha feito errado essa parte na hr de criar o formulário, e isso mesmo que estava me dando o problema que eu estava tentando resolver agr

2022-01-21 13:55 UTC, SamuelSsc commented on package.json
> +    "styled-components": "^5.3.3"
ahhh sim pode deixar

2022-01-26 15:37 UTC, dan-ueno commented on src/components/Login/Login.component.tsx
> +    <Forms id="Forms" >
id

2022-01-26 15:37 UTC, dan-ueno commented on src/components/Login/Login.component.tsx
> +      <Button id="btnEntrar"  type="submit" >Entrar</Button>
id

2022-01-26 15:38 UTC, dan-ueno approved these changes
acho que está ok o componente, mas tira esses ids

2022-01-26 16:16 UTC, merged